@{
   LibraryChangesForVersion='2103'

   Url='https://docs.microsoft.com/en-us/powershell/sccm/2103-release-notes?view=sccm-ps'

   RemovedCmdletNames=@(
   )

   RemovedAliasNames=@(
   )

   UnsupportedPSCoreCommandNames=@(
      'Import-CMPackage',
      'Import-CMDriverPackage',
      'Import-CMTaskSequence',
      'Export-CMPackage',
      'Export-CMDriverPackage',
      'Export-CMTaskSequence'
   )

   DeprecatedCommandNames=@()

   UnresolvedBugCommandNames=@(
   )

   ChangedCommandNames=@(
      'Add-CMFallbackStatusPoint'
      'Copy-CMCollection'
      'Get-CMDeploymentStatusDetails'
      'Get-CMDriver'
      'Get-CMPackage'
      'Get-CMSoftwareUpdateDeployment'
      'New-CMApplication'
      'New-CMCertificateProfileScep'
      'New-CMCollection'
      'New-CMOperatingSystemImage'
      'New-CMOperatingSystemInstaller'
      'New-CMTSRule'
      'New-CMTSStepConditionVariable'
      'New-CMSoftwareUpdateAutoDeploymentRule'
      'Set-CMCertificateProfileScep'
      'Set-CMClientPushInstallation'
      'Set-CMCollection'
      'Set-CMEmailProfile'
      'Set-CMFallbackStatusPoint'
      'Set-CMThirdPartyUpdateCatalog'
      'Set-CMThirdPartyUpdateCategory'
      'Set-CMTSStepApplyDataImage'
      'Set-CMTSStepApplyDriverPackage'
      'Set-CMTSStepApplyNetworkSetting'
      'Set-CMTSStepApplyOperatingSystem'
      'Set-CMTSStepApplyWindowsSetting'
      'Set-CMTSStepAutoApplyDriver'
      'Set-CMTSStepCaptureNetworkSettings'
      'Set-CMTSStepCaptureSystemImage'
      'Set-CMTSStepCaptureUserState'
      'Set-CMTSStepCaptureWindowsSettings'
      'Set-CMTSStepConnectNetworkFolder'
      'Set-CMTSStepConvertDisk'
      'Set-CMTSStepDisableBitLocker'
      'Set-CMTSStepDownloadPackageContent'
      'Set-CMTSStepEnableBitLocker'
      'Set-CMTSStepInstallApplication'
      'Set-CMTSStepInstallSoftware'
      'Set-CMTSStepInstallUpdate'
      'Set-CMTSStepJoinDomainWorkgroup'
      'Set-CMTSStepOfflineEnableBitLocker'
      'Set-CMTSStepPartitionDisk'
      'Set-CMTSStepPrepareConfigMgrClient'
      'Set-CMTSStepPrepareWindows'
      'Set-CMTSStepPrestartCheck'
      'Set-CMTSStepReboot'
      'Set-CMTSStepReleaseStateStore'
      'Set-CMTSStepRequestStateStore'
      'Set-CMTSStepRestoreUserState'
      'Set-CMTSStepRunCommandLine'
      'Set-CMTSStepRunPowerShellScript'
      'Set-CMTSStepRunTaskSequence'
      'Set-CMTSStepSetDynamicVariable'
      'Set-CMTSStepSetupWindowsAndConfigMgr'
      'Set-CMTSStepSetVariable'
      'Set-CMTSStepUpgradeOperatingSystem'
       # following cmdlets add fast parameter, include 'Get-CMDriver'
      'Get-CMAlert'
      'Get-CMAlertSubscription'
      'Get-CMBaseline'
      'Get-CMBaselineDeployment'
      'Get-CMBaselineDeploymentStatus'
      'Get-CMClientCertificatePfx'
      'Get-CMComplianceRule'
      'Get-CMComplianceSetting'
      'Get-CMConfigurationPlatform'
      'Get-CMConfigurationPolicyDeployment'
      'Get-CMDriverPackage'
      'Get-CMTaskSequence'
      'Get-CMTaskSequenceDeployment'
  )

   BreakingChangesCommandNames=@(
      'New-CMSoftwareUpdateAutoDeploymentRule'
      'Set-CMSoftwareUpdateAutoDeploymentRule'
   )
}
